config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :cards do
    resources :notes
  end
  resources :appointments
  resources :departaments
  root to: "home#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.has_role? :admin
        can :manage, :all
      end

      if user.has_role? :registry
        can [:read, :create], Card
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
validates :user_id, :card_id, presence: :true
belongs_to :user
belongs_to :card
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :appointments
  has_many :notes, dependent: :destroy
  has_many :users, through: :appointments
  validates :f_name, :l_name, :birthday, :gender, presence: :true
end

app/models/departament.rb
class Departament < ApplicationRecord
  has_many :users
end

app/models/note.rb
class Note < ApplicationRecord
# belongs_to :user
belongs_to :card
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles
# belongs_to :resource, :polymorphic => true
scopify
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  rolify
  has_many :appointments
  has_many :cards, through: :appointments
  belongs_to :departament
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, alert: exception.message
  end


  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
    @appointments = Appointment.all
  end

  def new
    @appointment = Appointment.new
    @departaments = Departament.all
    @patients = Card.all
    @users = []
    if params[:departament].present?
      @users = User.where(departament: params[:departament])
    end
    if request.xhr?
      respond_to do |format|
      format.json {
      render json: {users: @users}
      }
      end
    end
  end

  def create
    # binding.pry
    @appointment = Appointment.new(appointment_params)
    if @appointment.save || @appointment.valid?
      redirect_to appointments_path, notice: t("notice.card.created")
    else
      @appointment = Appointment.new(appointment_params)
      @departaments = Departament.all
      @patients = Card.all
      @users = []
      flash.now[:error] =  t("errors.appointment.fill")
      render action: :new
    end
  end

  private

  def appointment_params
    params.require(:appointment).permit(:user_id, :card_id, :meeting_time)
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def index
    @cards = Card.all
  end

  def new
    authorize! :new, Card
    @card = Card.new
  end

  def create
    authorize! :create, Card
    @card = Card.new(card_params)

    if @card.save
      redirect_to cards_path, notice: t("notice.card.created")
    else
      render action: :new
    end
  end

  def show
    @card = Card.find(params[:id])
    @notes = @card.notes
  end

  private

  def card_params
    params.require(:card).permit(:f_name, :m_name, :l_name, :birthday, :tel, :gender)
  end
end

app/controllers/departaments_controller.rb
class DepartamentsController < ApplicationController
  before_action :load_departament, only: [:edit, :show, :update, :destroy]

  def index
    @departaments = Departament.all.order(:name)
  end

  def show
    render
  end

  def new
    @departament = Departament.new
    authorize! :new, @departament
  end

  def create
    @departament = Departament.new(departament_params)
    authorize! :new, @departament
    if @departament.save
      redirect_to departaments_path, notice: t("notice.departament.created")
    else
      render action: :new
    end
  end

  def edit
    authorize! :edit, @departament
    render
  end

  def update
    authorize! :update, @departament
    if @departament.update(departament_params)
      redirect_to departaments_path, notice: t("notice.departament.updated")
    else
      render action: :new
    end
  end

  def destroy
    authorize! :destroy, @departament
    @departament.destroy
    redirect_to departaments_path, notice: t("notice.departament.deleted")
  end

  private

  def departament_params
    params.require(:departament).permit(:name)
  end

  def load_departament
    @departament = Departament.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
before_action :load_card

  def new
    @note = Note.new
  end

  def create
    @note =  Note.new(note_params)
    @note.card = @card
    if @note.save
      redirect_to card_path(@card), notice: t("notice.note.created")
    else
      render action: :new
    end
  end

  def show
    
  end

private
  def note_params
    params.require(:note).permit(:name, :description, :card_id)
  end

  def load_card
    @card = Card.find(params[:card_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(path)
    current_route = Rails.application.routes.recognize_path(path)
    "active" if current_page?(path) or params[:controller] == current_route[:controller]
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/departaments_helper.rb
module DepartamentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/_form.html.haml
=simple_form_for(@appointment, html: { class: 'form-horizontal, new-appointments-form' }) do |f|
  = f.input :meeting_time, minute_step: 15, start_hour: 9, end_hour: 18, as: :datetime
  -# = binding.pry
  .appointment-select
    %label{for: "appointment_card"}

      %select{ class: "js-select-2", name: "appointment[card_id]", id: "appointment_card" }
        %option{disabled: :disabled, selected: :selected } Select patient
        - @patients.each do |u|
          %option{ @appointment.card == u ? {selected: :selected} : {}, value: u.id}= u.f_name
  .appointment-select
    %label{for: "appointment_departament"}
      %select{ class: "js-select-2", id: "appointment_departament" }
        %option{disabled: :disabled, selected: :selected } Select Departament
        - @departaments.each do |d|
          %option{ value: d.id }= d.name
  .appointment-select
    %label{for: "appointment_user"}
      %select{class: "js-select-2", name: "appointment[user_id]", id: "appointment_user"}
        %option{disabled: :disabled, selected: :selected } Select doctor
        - @users.each do |u|
          %option{value: u.id}= u.name

  = f.submit "Створити запис", class: "btn btn-success"

:javascript
  $(document).ready(function() {
      $('.js-select-2').select2({ width: '100%' });
  });

app/views/appointments/index.haml
%ul.breadcrumb
  %li
    = link_to t("index"), root_path
    %span.divider
  %li.active
    = t("appointment.plural")

= link_to t("appointment.new"), new_appointment_path

- @appointments.each do |a|
  .app
    = a.user.name
    = a.meeting_time
    = a.card.f_name

app/views/appointments/new.haml
%ul.breadcrumb
  %li
    = link_to t('index'), root_path
    %span.divider
  %li
    = link_to t('appointment.plural'), appointments_path
  %li.active
    = t('appointment.new')
.div-centered
  = render 'appointments/form'

app/views/cards/_form.haml
= simple_form_for(@card, html: { class: 'form-horizontal, new-cards-form' }) do |f|
  = f.input :f_name, label: t('card.new_card.f_name')
  = f.input :m_name, label: t('card.new_card.m_name')
  = f.input :l_name, label: t('card.new_card.l_name')
  = f.input :birthday, as: :date, start_year: Time.now.year - 110, end_year: Time.now.year, label: t('card.new_card.b_day')
  = f.input :tel, as: :tel, label: t('card.new_card.tel')
  = f.input :gender, as: :radio_buttons, collection: [['0', 'Жіноча'], ['1', 'Чоловіча']], label_method: :second, value_method: :first, label: t('card.new_card.gender')

  = f.submit t('card.new_card.create'), class: "btn btn-success"

app/views/cards/index.html.haml
%ul.breadcrumb
  %li
    =link_to t("index"), root_path
    %span.divider
  %li.active
    =t("card.plural")
= link_to "Нова медична картка пацієнта", new_card_path, class: "btn btn-primary"
.cards
  - @cards.each do |c|
    .card
      %p Прізвище: #{c.l_name}
      %p Ім'я: #{c.f_name}
      %p По-батькові: #{c.m_name}
      %p Телефон: #{c.tel}
      = link_to "Більше...", card_path(c)

app/views/cards/new.html.haml
%ul.breadcrumb
  %li
    =link_to t("index"), root_path
    %span.divider
  %li
    =link_to t("card.plural"), cards_path
    %span.divider
  %li.active
    =t("card.new")
.div-centered
  = render 'cards/form'

app/views/cards/show.haml
%ul.breadcrumb
  %li
    =link_to t('index'), root_path
    %span.divider
  %li
    =link_to t('card.plural'), cards_path
    %span.divider
  %li.active
    = @card.l_name + ' ' + @card.f_name

.all-notes
  - @notes.each do |note|
    .note
      .note-title
        %h6 Title
        = note.name
      .note-desc
        %h6 Description
        = note.description
      .note-link
        =link_to "Details", card_note_path(note)
.new-note
  =link_to "New note", new_card_note_path(@card)

app/views/departaments/_form.haml
= simple_form_for(@departament, html: { class: 'form-horizontal, new-cards-form' }) do |f|
  = f.input :name
  = f.submit @departament.persisted? ? t('departament.update') : t('departament.create'), class: 'btn btn-success'

app/views/departaments/edit.haml
%ul.breadcrumb
  %li
    =link_to t("menu.departament.plural"), departaments_path
    %span.divider
  %li.active
    =t("departament.new")
= render 'departaments/form'

app/views/departaments/index.haml
.button{style: "padding: 15px;"}
  = link_to t("departament.new"), new_departament_path, class: "btn btn-primary"
%table.table.table-hover
  %tr
    %th Назва відділу
    %th Кількість лікарів
    %th

  - @departaments.each do |d|
    %tr
      %td= link_to d.name, departament_path(d)
      %td= d.users.count
      %td.span2
        .btn-group.btn-group-sm.pull-right
          = link_to t("action.edit"), edit_departament_path(d), class: 'btn btn-success'
          = link_to t("action.delete"), departament_path(d), data: { confirm: "Are you sure?" }, method: :delete, class: 'btn btn-mini btn-danger'

app/views/departaments/new.haml
%ul.breadcrumb
  %li
    =link_to t("menu.departament.plural"), departaments_path
    %span.divider
  %li.active
    =t("departament.new")
= render 'departaments/form'

app/views/departaments/show.haml
%ul.breadcrumb
  %li
    =link_to t("menu.departament.plural"), departaments_path
    %span.divider
  %li.active
    = @departament.name

app/views/home/_registry_navigation.haml
.sa
.main-navigation
  .main-navigation-item
    =link_to appointments_path do
      .navigation-item-link #{ t("appointment.plural") }
  .main-navigation-item
    =link_to cards_path do
      .navigation-item-link #{ t("card.plural") }
  .main-navigation-item
    =link_to "#{}" do
      .navigation-item-link Other

app/views/home/_team_member_navigation.haml
assad

app/views/home/index.html.haml
- if current_user.has_role? :registry
  = render 'home/registry_navigation'
- if current_user.has_role? :team_member
  = render 'home/team_member_navigation'
- if current_user.has_role? :member
  = render 'home/member_navigation'

app/views/notes/_form.haml
= simple_form_for([@card, @note], html: { class: 'form-horizontal, new-cards-form' }) do |f|
  = f.input :name
  = f.input :description
  = f.submit "Create", class: "btn btn-success"

app/views/notes/new.haml
= render 'form'

app/views/users/index.haml
%table.table.table-hover
  %tr
    %th Лікар
    %th Номер телефону
    %th E-mail
    %th Відділення
    %th

  - @users.each do |u|
    %tr
      %td= link_to u.name, user_path(u)
      %td= u.tel
      %td= u.email
      %td= u.departament.name
      %td.span2
        .btn-group.btn-group-sm.pull-right
          = link_to t("action.delete"), user_path(u), data: { confirm: "Are you sure?" }, method: :delete, class: 'btn btn-mini btn-danger'

app/views/users/show.haml
%ul.breadcrumb
  %li
    =link_to t("menu.user.plural"), users_path
    %span.divider
  %li.active
    = @user.name


майбутня інформація про користувача