config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :cards do
    resources :notes
  end
  resources :appointments
  resources :departaments
  root to: "home#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.has_role? :admin
        can :manage, :all
      end

      if user.has_role? :registry
        can [:read, :create], Card
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
validates :user_id, :card_id, presence: :true
belongs_to :user
belongs_to :card
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :appointments
  has_many :notes, dependent: :destroy
  has_many :users, through: :appointments
  validates :f_name, :l_name, :birthday, :gender, presence: :true
end

app/models/departament.rb
class Departament < ApplicationRecord
  has_many :users
end

app/models/note.rb
class Note < ApplicationRecord
# belongs_to :user
belongs_to :card
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles
# belongs_to :resource, :polymorphic => true
scopify
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  rolify
  has_many :appointments
  has_many :cards, through: :appointments
  belongs_to :departament
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, alert: exception.message
  end


  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def index
    @cards = Card.all
  end

  def new
    authorize! :new, Card
    @card = Card.new
  end

  def create
    authorize! :create, Card
    @card = Card.new(card_params)

    if @card.save
      redirect_to cards_path, notice: t("notice.card.created")
    else
      render action: :new
    end
  end

  def show
    @card = Card.find(params[:id])
    @notes = @card.notes
  end

  private

  def card_params
    params.require(:card).permit(:f_name, :m_name, :l_name, :birthday, :tel, :gender)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
before_action :load_card

  def new
    @note = Note.new
  end

  def create
    @note =  Note.new(note_params)
    @note.card = @card
    if @note.save
      redirect_to card_path(@card), notice: t("notice.note.created")
    else
      render action: :new
    end
  end

  def show
    
  end

private
  def note_params
    params.require(:note).permit(:name, :description, :card_id)
  end

  def load_card
    @card = Card.find(params[:card_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(path)
    current_route = Rails.application.routes.recognize_path(path)
    "active" if current_page?(path) or params[:controller] == current_route[:controller]
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/departaments_helper.rb
module DepartamentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-#{name.to_s == 'notice' ? "success" : "danger"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/_navigation.haml
.navigation-bar
  %ul.nav.navbar-nav
    %li= link_to 'LOGO', root_path
  %ul.nav.nav-pills
    - if user_signed_in? && current_user.has_role?(:admin)
      %li{class: active_class(departaments_path)}= link_to t('menu.departament.plural'), departaments_path
      %li{class: active_class(users_path)}= link_to t('menu.user.plural'), users_path
      %li{class: active_class(cards_path)}= link_to t('menu.card.plural'), cards_path
    - if user_signed_in?
      %li= link_to('Logout', destroy_user_session_path, method: :delete)
    - else
      %li= link_to('Login', new_user_session_path)

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title Dent
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    %link{:href => "https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,600", :rel => "stylesheet"}
    = csrf_meta_tags
  %body
    .container
      = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        = render 'layouts/messages'
        = yield
      .container
        %footer
          %hr
          &copy; 2017 - #{Date.today.year} Dentistry